"""Table fotos and categories

Revision ID: 4db3e96d597e
Revises: 5709020be724
Create Date: 2024-11-26 11:44:09.626532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db3e96d597e'
down_revision: Union[str, None] = '5709020be724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_auction', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['id_auction'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_auction', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['id_auction'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('auctions_id_user_fkey', 'auctions', type_='foreignkey')
    op.create_foreign_key(None, 'auctions', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auctions', type_='foreignkey')
    op.create_foreign_key('auctions_id_user_fkey', 'auctions', 'users', ['id_user'], ['id'])
    op.drop_table('fotos')
    op.drop_table('categories')
    # ### end Alembic commands ###
