"""Add table auctions

Revision ID: 5709020be724
Revises: 5f6372151f4c
Create Date: 2024-11-20 19:38:54.641867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5709020be724'
down_revision: Union[str, None] = '5f6372151f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('srart_price', sa.Numeric(), nullable=False),
    sa.Column('curr_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('finish_at', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auctions')
    # ### end Alembic commands ###
