"""Upgrade users table

Revision ID: 5f6372151f4c
Revises: a5a842944ed6
Create Date: 2024-11-19 22:35:20.472250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6372151f4c'
down_revision: Union[str, None] = 'a5a842944ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('users', 'balance')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
