"""Table coment and history. Add step bit in Auction

Revision ID: 87d607febacf
Revises: 4db3e96d597e
Create Date: 2024-11-26 12:48:46.315640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d607febacf'
down_revision: Union[str, None] = '4db3e96d597e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_auction', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('coment', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['id_auction'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_auction', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('bit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['id_auction'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auctions', sa.Column('step_bit', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'step_bit')
    op.drop_table('user_bits')
    op.drop_table('coments')
    # ### end Alembic commands ###
